<#
.SYNOPSIS
  Converts Markdown → PDF, applies header/footer, and generates SHA256 hash.
  Falls back to text-only PDF if TeX engine not found.
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory)][string]$SourceMd,
  [string]$OutDir = "docs/releases",
  [switch]$NoFormat
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $PSCommandPath
$Templates = Join-Path $ScriptDir "../docs/templates"
$Header = Join-Path $Templates "header.md"
$Footer = Join-Path $Templates "footer.md"

if (-not (Test-Path $SourceMd)) { throw "Source file not found: $SourceMd" }
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }

if (-not $NoFormat) {
    $formatter = Join-Path $ScriptDir "run-formatter.ps1"
    if (Test-Path $formatter) { & $formatter -Source $SourceMd }
}

$temp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + ".md")
@(
    if (Test-Path $Header) { Get-Content $Header -Raw } else { "" }
    Get-Content $SourceMd -Raw
    if (Test-Path $Footer) { Get-Content $Footer -Raw } else { "" }
) | Set-Content -Encoding UTF8 -Path $temp

$pdfName = (Split-Path $SourceMd -LeafBase) + ".pdf"
$pdfFile = Join-Path $OutDir $pdfName

# --- Detect TeX / PDF engine ---
if (Get-Command xelatex -ErrorAction SilentlyContinue) {
    $engine = 'xelatex'
} elseif (Get-Command wkhtmltopdf -ErrorAction SilentlyContinue) {
    $engine = 'wkhtmltopdf'
} else {
    $engine = $null
}

try {
    if ($engine) {
        Write-Host "📄 Converting $SourceMd → $pdfFile (engine: $engine)"
        pandoc $temp -o $pdfFile --standalone --pdf-engine=$engine --quiet
    } else {
        Write-Warning "⚠️ No TeX or HTML PDF engine found — creating placeholder text PDF."
        $content = "[PMDocu-DR Placeholder PDF — install TeX for full rendering]`n`n" + (Get-Content -Raw $temp)
        Set-Content -Path $pdfFile -Value $content -Encoding UTF8
    }

    if (-not (Test-Path $pdfFile)) { throw "PDF not created: $pdfFile" }

    $hashFile = "$pdfFile.sha256"
    $hash = (Get-FileHash -Algorithm SHA256 $pdfFile).Hash
    $hash | Out-File -Encoding ascii $hashFile

    Write-Host "✅ PDF built: $pdfFile"
    Write-Host "🔐 SHA256  : $hashFile"
}
finally {
    Remove-Item -Path $temp -Force -ErrorAction SilentlyContinue
}

# SIG # Begin signature block
# MIIb3QYJKoZIhvcNAQcCoIIbzjCCG8oCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUb4A1M74VgRiU3H/JojZq4HCe
# iJSgghZKMIIDDDCCAfSgAwIBAgIQWygODpAbH7FEXnXEAhkixDANBgkqhkiG9w0B
# AQsFADAeMRwwGgYDVQQDDBNIeXBlclYtRFIgTG9jYWwgRGV2MB4XDTI1MTAxMjE3
# NDQxNloXDTI2MTAxMjE4MDQxNlowHjEcMBoGA1UEAwwTSHlwZXJWLURSIExvY2Fs
# IERldjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANeWzrTEP0aVY8Ae
# bRXyika6Mu099n13IdB8BNKiQ2mK+l9DQNTu6TYO/5I5YBORTra/LuKJOLp5cC4G
# qyw2IBzuOluoc444ww9o4NckY5dxba+o6/sI0JogSbhaLINYbbnYVxb9VeY2w9Gx
# 1050hEPDrGj4HUtXNajS0Gxha+Y2tmV+LGcUInS0TIt/eOKqXT32NOme6kVJCt9V
# ULBSzUkTZDUmM/8n8Ow09z4Sf3RYFRQv5sSG9/F9PC+IOjxCwmluD9Pa9uEYyC3x
# P2S88aXpO7Uzb7hfAxx1cFN+yGEEB/T237fg4ZbdMINFS8zxuD3snWyBOzy5BKdh
# GvCXXDkCAwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUF
# BwMDMB0GA1UdDgQWBBRYoFdAdeM5Ns7JIXsLwc5eYxhKujANBgkqhkiG9w0BAQsF
# AAOCAQEAP9ICSl+XqfQmW4BL18FKte+Jt8KZpLt6fpmiYdiqFlnj5cxqZUdTGlBz
# 4mesg+HC9hDPpGlyvg9EaqGF47Xa7gvsPZPXGs+Rkw12oMFm2kCuDlpx30PuWHTy
# CCxS8YmGtviaLFlQP0tBVj6o3cKYQgcE4EJbaBS/PEeAwDjpI63k4/q0XwugaaSU
# 56i+vj+iezXrrvdxXBcG1biLtheFyWEfZZ+3tt6KzNJZmZBWpTNvEQlEgFxPFaTs
# Dd0ZO7SvErtsJzlIgHbCJspxmumqKBdqdAySs2vTcBKVYI8mwITCi+nK/vxIZZWo
# GOo+TtcUa3CO9cLDqxfUo0hEhrguoTCCBY0wggR1oAMCAQICEA6bGI750C3n79tQ
# 4ghAGFowDQYJKoZIhvcNAQEMBQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERp
# Z2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMb
# RGlnaUNlcnQgQXNzdXJlZCBJRCBSb290IENBMB4XDTIyMDgwMTAwMDAwMFoXDTMx
# MTEwOTIzNTk1OVowYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IElu
# YzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQg
# VHJ1c3RlZCBSb290IEc0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# v+aQc2jeu+RdSjwwIjBpM+zCpyUuySE98orYWcLhKac9WKt2ms2uexuEDcQwH/Mb
# pDgW61bGl20dq7J58soR0uRf1gU8Ug9SH8aeFaV+vp+pVxZZVXKvaJNwwrK6dZlq
# czKU0RBEEC7fgvMHhOZ0O21x4i0MG+4g1ckgHWMpLc7sXk7Ik/ghYZs06wXGXuxb
# Grzryc/NrDRAX7F6Zu53yEioZldXn1RYjgwrt0+nMNlW7sp7XeOtyU9e5TXnMcva
# k17cjo+A2raRmECQecN4x7axxLVqGDgDEI3Y1DekLgV9iPWCPhCRcKtVgkEy19sE
# cypukQF8IUzUvK4bA3VdeGbZOjFEmjNAvwjXWkmkwuapoGfdpCe8oU85tRFYF/ck
# XEaPZPfBaYh2mHY9WV1CdoeJl2l6SPDgohIbZpp0yt5LHucOY67m1O+SkjqePdwA
# 5EUlibaaRBkrfsCUtNJhbesz2cXfSwQAzH0clcOP9yGyshG3u3/y1YxwLEFgqrFj
# GESVGnZifvaAsPvoZKYz0YkH4b235kOkGLimdwHhD5QMIR2yVCkliWzlDlJRR3S+
# Jqy2QXXeeqxfjT/JvNNBERJb5RBQ6zHFynIWIgnffEx1P2PsIV/EIFFrb7GrhotP
# wtZFX50g/KEexcCPorF+CiaZ9eRpL5gdLfXZqbId5RsCAwEAAaOCATowggE2MA8G
# A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOzX44LScV1kTN8uZz/nupiuHA9PMB8G
# A1UdIwQYMBaAFEXroq/0ksuCMS1Ri6enIZ3zbcgPMA4GA1UdDwEB/wQEAwIBhjB5
# BggrBgEFBQcBAQRtMGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0
# LmNvbTBDBggrBgEFBQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0Rp
# Z2lDZXJ0QXNzdXJlZElEUm9vdENBLmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRw
# Oi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3Js
# MBEGA1UdIAQKMAgwBgYEVR0gADANBgkqhkiG9w0BAQwFAAOCAQEAcKC/Q1xV5zhf
# oKN0Gz22Ftf3v1cHvZqsoYcs7IVeqRq7IviHGmlUIu2kiHdtvRoU9BNKei8ttzjv
# 9P+Aufih9/Jy3iS8UgPITtAq3votVs/59PesMHqai7Je1M/RQ0SbQyHrlnKhSLSZ
# y51PpwYDE3cnRNTnf+hZqPC/Lwum6fI0POz3A8eHqNJMQBk1RmppVLC4oVaO7KTV
# Peix3P0c2PR3WlxUjG/voVA9/HYJaISfb8rbII01YBwCA8sgsKxYoA5AY8WYIsGy
# WfVVa88nq2x2zm8jLfR+cWojayL/ErhULSd+2DrZ8LaHlv1b0VysGMNNn3O3Aamf
# V6peKOK5lDCCBrQwggScoAMCAQICEA3HrFcF/yGZLkBDIgw6SYYwDQYJKoZIhvcN
# AQELBQAwYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcG
# A1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3Rl
# ZCBSb290IEc0MB4XDTI1MDUwNzAwMDAwMFoXDTM4MDExNDIzNTk1OVowaTELMAkG
# A1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMUEwPwYDVQQDEzhEaWdp
# Q2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGluZyBSU0E0MDk2IFNIQTI1NiAyMDI1
# IENBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALR4MdMKmEFyvjxG
# wBysddujRmh0tFEXnU2tjQ2UtZmWgyxU7UNqEY81FzJsQqr5G7A6c+Gh/qm8Xi4a
# PCOo2N8S9SLrC6Kbltqn7SWCWgzbNfiR+2fkHUiljNOqnIVD/gG3SYDEAd4dg2dD
# GpeZGKe+42DFUF0mR/vtLa4+gKPsYfwEu7EEbkC9+0F2w4QJLVSTEG8yAR2CQWIM
# 1iI5PHg62IVwxKSpO0XaF9DPfNBKS7Zazch8NF5vp7eaZ2CVNxpqumzTCNSOxm+S
# AWSuIr21Qomb+zzQWKhxKTVVgtmUPAW35xUUFREmDrMxSNlr/NsJyUXzdtFUUt4a
# S4CEeIY8y9IaaGBpPNXKFifinT7zL2gdFpBP9qh8SdLnEut/GcalNeJQ55IuwnKC
# gs+nrpuQNfVmUB5KlCX3ZA4x5HHKS+rqBvKWxdCyQEEGcbLe1b8Aw4wJkhU1JrPs
# FfxW1gaou30yZ46t4Y9F20HHfIY4/6vHespYMQmUiote8ladjS/nJ0+k6Mvqzfpz
# PDOy5y6gqztiT96Fv/9bH7mQyogxG9QEPHrPV6/7umw052AkyiLA6tQbZl1KhBtT
# asySkuJDpsZGKdlsjg4u70EwgWbVRSX1Wd4+zoFpp4Ra+MlKM2baoD6x0VR4RjSp
# WM8o5a6D8bpfm4CLKczsG7ZrIGNTAgMBAAGjggFdMIIBWTASBgNVHRMBAf8ECDAG
# AQH/AgEAMB0GA1UdDgQWBBTvb1NK6eQGfHrK4pBW9i/USezLTjAfBgNVHSMEGDAW
# gBTs1+OC0nFdZEzfLmc/57qYrhwPTzAOBgNVHQ8BAf8EBAMCAYYwEwYDVR0lBAww
# CgYIKwYBBQUHAwgwdwYIKwYBBQUHAQEEazBpMCQGCCsGAQUFBzABhhhodHRwOi8v
# b2NzcC5kaWdpY2VydC5jb20wQQYIKwYBBQUHMAKGNWh0dHA6Ly9jYWNlcnRzLmRp
# Z2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRSb290RzQuY3J0MEMGA1UdHwQ8MDow
# OKA2oDSGMmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRS
# b290RzQuY3JsMCAGA1UdIAQZMBcwCAYGZ4EMAQQCMAsGCWCGSAGG/WwHATANBgkq
# hkiG9w0BAQsFAAOCAgEAF877FoAc/gc9EXZxML2+C8i1NKZ/zdCHxYgaMH9Pw5tc
# BnPw6O6FTGNpoV2V4wzSUGvI9NAzaoQk97frPBtIj+ZLzdp+yXdhOP4hCFATuNT+
# ReOPK0mCefSG+tXqGpYZ3essBS3q8nL2UwM+NMvEuBd/2vmdYxDCvwzJv2sRUoKE
# fJ+nN57mQfQXwcAEGCvRR2qKtntujB71WPYAgwPyWLKu6RnaID/B0ba2H3LUiwDR
# AXx1Neq9ydOal95CHfmTnM4I+ZI2rVQfjXQA1WSjjf4J2a7jLzWGNqNX+DF0SQzH
# U0pTi4dBwp9nEC8EAqoxW6q17r0z0noDjs6+BFo+z7bKSBwZXTRNivYuve3L2oiK
# NqetRHdqfMTCW/NmKLJ9M+MtucVGyOxiDf06VXxyKkOirv6o02OoXN4bFzK0vlNM
# svhlqgF2puE6FndlENSmE+9JGYxOGLS/D284NHNboDGcmWXfwXRy4kbu4QFhOm0x
# JuF2EZAOk5eCkhSxZON3rGlHqhpB/8MluDezooIs8CVnrpHMiD2wL40mm53+/j7t
# FaxYKIqL0Q4ssd8xHZnIn/7GELH3IdvG2XlM9q7WP/UwgOkw/HQtyRN62JK4S1C8
# uw3PdBunvAZapsiI5YKdvlarEvf8EA+8hcpSM9LHJmyrxaFtoza2zNaQ9k+5t1ww
# ggbtMIIE1aADAgECAhAKgO8YS43xBYLRxHanlXRoMA0GCSqGSIb3DQEBCwUAMGkx
# CzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4
# RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYg
# MjAyNSBDQTEwHhcNMjUwNjA0MDAwMDAwWhcNMzYwOTAzMjM1OTU5WjBjMQswCQYD
# VQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRpZ2lD
# ZXJ0IFNIQTI1NiBSU0E0MDk2IFRpbWVzdGFtcCBSZXNwb25kZXIgMjAyNSAxMIIC
# IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0EasLRLGntDqrmBWsytXum9R
# /4ZwCgHfyjfMGUIwYzKomd8U1nH7C8Dr0cVMF3BsfAFI54um8+dnxk36+jx0Tb+k
# +87H9WPxNyFPJIDZHhAqlUPt281mHrBbZHqRK71Em3/hCGC5KyyneqiZ7syvFXJ9
# A72wzHpkBaMUNg7MOLxI6E9RaUueHTQKWXymOtRwJXcrcTTPPT2V1D/+cFllESvi
# H8YjoPFvZSjKs3SKO1QNUdFd2adw44wDcKgH+JRJE5Qg0NP3yiSyi5MxgU6cehGH
# r7zou1znOM8odbkqoK+lJ25LCHBSai25CFyD23DZgPfDrJJJK77epTwMP6eKA0kW
# a3osAe8fcpK40uhktzUd/Yk0xUvhDU6lvJukx7jphx40DQt82yepyekl4i0r8OEp
# s/FNO4ahfvAk12hE5FVs9HVVWcO5J4dVmVzix4A77p3awLbr89A90/nWGjXMGn7F
# QhmSlIUDy9Z2hSgctaepZTd0ILIUbWuhKuAeNIeWrzHKYueMJtItnj2Q+aTyLLKL
# M0MheP/9w6CtjuuVHJOVoIJ/DtpJRE7Ce7vMRHoRon4CWIvuiNN1Lk9Y+xZ66laz
# s2kKFSTnnkrT3pXWETTJkhd76CIDBbTRofOsNyEhzZtCGmnQigpFHti58CSmvEyJ
# cAlDVcKacJ+A9/z7eacCAwEAAaOCAZUwggGRMAwGA1UdEwEB/wQCMAAwHQYDVR0O
# BBYEFOQ7/PIx7f391/ORcWMZUEPPYYzoMB8GA1UdIwQYMBaAFO9vU0rp5AZ8esri
# kFb2L9RJ7MtOMA4GA1UdDwEB/wQEAwIHgDAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDCBlQYIKwYBBQUHAQEEgYgwgYUwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
# Z2ljZXJ0LmNvbTBdBggrBgEFBQcwAoZRaHR0cDovL2NhY2VydHMuZGlnaWNlcnQu
# Y29tL0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0YW1waW5nUlNBNDA5NlNIQTI1NjIw
# MjVDQTEuY3J0MF8GA1UdHwRYMFYwVKBSoFCGTmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0
# LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVTdGFtcGluZ1JTQTQwOTZTSEEyNTYy
# MDI1Q0ExLmNybDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwDQYJ
# KoZIhvcNAQELBQADggIBAGUqrfEcJwS5rmBB7NEIRJ5jQHIh+OT2Ik/bNYulCrVv
# hREafBYF0RkP2AGr181o2YWPoSHz9iZEN/FPsLSTwVQWo2H62yGBvg7ouCODwrx6
# ULj6hYKqdT8wv2UV+Kbz/3ImZlJ7YXwBD9R0oU62PtgxOao872bOySCILdBghQ/Z
# LcdC8cbUUO75ZSpbh1oipOhcUT8lD8QAGB9lctZTTOJM3pHfKBAEcxQFoHlt2s9s
# XoxFizTeHihsQyfFg5fxUFEp7W42fNBVN4ueLaceRf9Cq9ec1v5iQMWTFQa0xNqI
# tH3CPFTG7aEQJmmrJTV3Qhtfparz+BW60OiMEgV5GWoBy4RVPRwqxv7Mk0Sy4QHs
# 7v9y69NBqycz0BZwhB9WOfOu/CIJnzkQTwtSSpGGhLdjnQ4eBpjtP+XB3pQCtv4E
# 5UCSDag6+iX8MmB10nfldPF9SVD7weCC3yXZi/uuhqdwkgVxuiMFzGVFwYbQsiGn
# oa9F5AaAyBjFBtXVLcKtapnMG3VH3EmAp/jsJ3FVF3+d1SVDTmjFjLbNFZUWMXuZ
# yvgLfgyPehwJVxwC+UpX2MSey2ueIu9THFVkT+um1vshETaWyQo8gmBto/m3acaP
# 9QsuLj3FNwFlTxq25+T4QwX9xa6ILs84ZPvmpovq90K8eWyG2N01c4IhSOxqt81n
# MYIE/TCCBPkCAQEwMjAeMRwwGgYDVQQDDBNIeXBlclYtRFIgTG9jYWwgRGV2AhBb
# KA4OkBsfsURedcQCGSLEMAkGBSsOAwIaBQCgeDAYBgorBgEEAYI3AgEMMQowCKAC
# gAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcCAQsx
# DjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBRrTPib3FVCpYtLnLrUTfE6
# wzFLCzANBgkqhkiG9w0BAQEFAASCAQBKAi1j/+sNudpNmsB0Rx58PZWdPiaSyvAX
# BRdSK+JMosFhd+CV+L0mddlg/yirlOL8rETN3M4Nma/oAOx2INagrocPg3AfZmsT
# 2T6FIpF9T8T4d8Nf7PAkdPDejI4kzlse6wdLG/YCddc5Ey3ZvHubZcIAMiiEGgDW
# osapWtN3XFdLxpIeW38qO0t5fJ21LGyLi/5rEwkuytUGO1iEdYAzROpUkd/dLKvB
# 3j+3OuH5Q7p+lp5ScYlkpP/b0GuauQQGgQpuE1lxJihmMsA+UglO7rkJNoadWTto
# lbIoTu9ZY4Zi47deGf5cK1MmnBGVf+eVA2SKntRJlG8aJC7Os2uFoYIDJjCCAyIG
# CSqGSIb3DQEJBjGCAxMwggMPAgEBMH0waTELMAkGA1UEBhMCVVMxFzAVBgNVBAoT
# DkRpZ2lDZXJ0LCBJbmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRp
# bWVTdGFtcGluZyBSU0E0MDk2IFNIQTI1NiAyMDI1IENBMQIQCoDvGEuN8QWC0cR2
# p5V0aDANBglghkgBZQMEAgEFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEw
# HAYJKoZIhvcNAQkFMQ8XDTI1MTAxNTIyNDcyNFowLwYJKoZIhvcNAQkEMSIEIOFn
# q6tbZz/p4T/qgXH8yHMyGsEQbmGovVQSTZnyQ01JMA0GCSqGSIb3DQEBAQUABIIC
# AGcYoq9Zf/ZsMbBnVKRATonMGqYFe0o90vcjFJBWdYAF4j1Z/+FFkdgXeEANdpZE
# LUCW4m17T1Yimyo4MYLSQalaAivwccxySfyCuBqtKxhtMK14iP9psTMgCwf24nvu
# nRcLpqmyeECVYFdpyUNuAKbRgeNkgN5TuBtmdRQQB2SvvBOmKUfv6Y6qHURq7FE1
# Ix68DZu/DmA2JB/DxsYt4jt+7rZdW4FTp4gqJbb1NsUJ35X8h5x6UT9JcIHI9l27
# mgD9FXvhzyjtQUKGXfjA+2YfY3jkxD2fcNYp5ACNtbejCrNGWUjzEuYQ9pnwd8Vs
# 31nnoqGRCgaXL0133wU6s61fpdXgKuiqiASa4LamudpSJNM92BcpFv7ltIpQy5AM
# owdoa3UpZGJo4WnMdrCfyMEtReJ7ggGhNzDfrR8WQckVnlgWxvZSVjp/E1M+ZqoS
# BOalXSq7Au9zbMOSEmJdjLuJulFXGeh0Rw1103WWma/j5AWXg/q7ksnL3o1JASAT
# tZ0wKo6fMx8ybGGhIbA0jt/stkcVsqKwj5SlwDoNePKz30wS8Ggo/9B/lPTBygSo
# zAyLOZF1GqF0zMKXc6iBKCWk8KU8z8VuGo3KnMRgIqkJpIRWzSrsJiBID0/kcWJl
# tFOcCsmZsEc3ntN8X0yxueV5VNhzIzSgiYfhaqbChC82
# SIG # End signature block
