name: Build and Sign Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'
      - 'scripts/**'
      - 'formatters/**'
  workflow_dispatch:

jobs:
  build_sign:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout -----------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Install dependencies -----------------------------------------------
      - name: Install Pandoc, TeX, and GPG
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex \
            texlive-latex-recommended texlive-fonts-recommended gpg

      # --- Normalize Markdown --------------------------------------------------
      - name: Run Markdown Formatter
        run: |
          pwsh scripts/run-formatter.ps1 -Source docs `
            -Exclude "templates/*" -InformationAction Continue `
            | Tee-Object -FilePath logs/formatter.log

      # --- Verify environment --------------------------------------------------
      - name: Verify environment
        run: pwsh -File scripts/verify-env.ps1 || true

      # --- Build PDFs ----------------------------------------------------------
      - name: Build PDFs
        run: |
          pwsh -File scripts/build-doc.ps1 -SourceMd docs/examples/ChangeRequest.md
          pwsh -File scripts/build-doc.ps1 -SourceMd docs/examples/ImplementationPlan.md

      # --- Sign and Verify PDFs ------------------------------------------------
      - name: Sign and Verify PDFs
        run: |
          pwsh -File scripts/sign-gpg.ps1 -TargetFile docs/releases/ChangeRequest.pdf
          pwsh -File scripts/sign-gpg.ps1 -TargetFile docs/releases/ChangeRequest.pdf -Verify
          pwsh -File scripts/sign-gpg.ps1 -TargetFile docs/releases/ImplementationPlan.pdf
          pwsh -File scripts/sign-gpg.ps1 -TargetFile docs/releases/ImplementationPlan.pdf -Verify

      # --- Upload signed artifacts --------------------------------------------
      - name: Upload signed artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pm-docs-signed
          path: docs/releases/
