name: 🧹 Build and Sign Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: 'Build mode: quick (default), full (rebuild all), or strict (verbose)'
        required: false
        default: 'quick'
      fail_on_warning:
        description: 'Fail build on warnings (true/false)'
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: windows-latest
    name: Build and Sign Documents

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Detect changed Markdown files
        id: changes
        shell: pwsh
        run: |
          Write-Host "🔎 Checking for changed Markdown files..."
          $diffBase = if ('${{ github.event_name }}' -eq 'pull_request') { '${{ github.event.pull_request.base.sha }}' } else { 'HEAD~1' }
          $changedFiles = git diff --name-only $diffBase HEAD | Select-String '\.md$' | ForEach-Object { $_.ToString() }

          if (-not $changedFiles) {
              Write-Host "🟡 No Markdown changes detected — skipping document build."
              echo "changed=false" >> $env:GITHUB_OUTPUT
          } else {
              Write-Host "🧾 Changed Markdown files:"
              $changedFiles | ForEach-Object { Write-Host "  - $_" }
              echo "changed=true" >> $env:GITHUB_OUTPUT
          }

      - name: 🏗️ Build documentation
        if: steps.changes.outputs.changed == 'true'
        shell: pwsh
        run: |
          $mode = '${{ github.event.inputs.mode }}'
          $failOnWarning = ('${{ github.event.inputs.fail_on_warning }}' -eq 'true')

          Write-Host "🔧 Running Convert-PMDocuDRToPDF.ps1..."
          Write-Host "🔹 Mode: $mode"
          Write-Host "🔹 Fail on Warning: $failOnWarning"

          if ($mode -eq 'strict') { $VerbosePreference = 'Continue' }

          pwsh -File "scripts/Convert-PMDocuDRToPDF.ps1"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "❌ Document conversion failed."
              exit 1
          }
      - name: 🔍 Validate Build Evidence
        shell: pwsh
        run: |
          Write-Information "[ci-docs] Verifying JSON build evidence..."
          $files = Get-ChildItem 'docs/_evidence' -Filter 'BuildResult-*.json' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $files) { Write-Error "[ci-docs] ❌ No build evidence found."; exit 1 }

          try {
              $null = Get-Content $files.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
              Write-Information "[ci-docs] ✅ $($files.Name) is valid JSON."
          } catch {
              Write-Error "[ci-docs] ❌ Invalid or unreadable build evidence file."
              exit 1
          }


          Write-Host "✅ Base document set built successfully."

      - name: 🧾 Build CI Compliance Matrix
        if: steps.changes.outputs.changed == 'true'
        shell: pwsh
        run: |
          pwsh -File "scripts/Convert-PMDocuDRToPDF.ps1" `
            -InputFile "docs/gov/CI-Compliance-Matrix.md" `
            -OutDir "docs/releases"

          if ($LASTEXITCODE -ne 0) {
              Write-Error "❌ CI Compliance Matrix build failed."
              exit 1
          }
          Write-Host "✅ CI Compliance Matrix built successfully."

      - name: 📜 Upload generated PDFs
        if: steps.changes.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: docs/releases/*.pdf
          retention-days: 30
