name: 🧹 Lint PowerShell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-powershell:
    name: Analyze PowerShell Scripts
    runs-on: windows-latest

    steps:
      - name: 🧩 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧰 Initialize PowerShell Analyzer
        shell: pwsh
        run: |
          Write-Output "=== Verifying PSScriptAnalyzer installation ==="
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser -AllowClobber
          Import-Module PSScriptAnalyzer -Force
          Get-Module PSScriptAnalyzer | Select Name, Version

      - name: 🔍 Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $Settings = "config/PSScriptAnalyzerSettings.psd1"
          $OutDir   = "docs/_evidence/lint"
          if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }

          Write-Output "=== Running analyzer with settings: $Settings ==="
          $Results = Invoke-ScriptAnalyzer -Path "scripts" -Settings $Settings -Recurse -ErrorAction Continue

          $JsonPath = Join-Path $OutDir ("lint-powershell-report_{0:yyyyMMdd_HHmmss}.json" -f (Get-Date))
          $TxtPath  = [IO.Path]::ChangeExtension($JsonPath, ".txt")

          $Results | ConvertTo-Json -Depth 5 | Out-File -FilePath $JsonPath -Encoding utf8 -Force
          $Results | Out-File -FilePath $TxtPath -Encoding utf8 -Force

          Write-Output "Reports generated:"
          Write-Output " - JSON: $JsonPath"
          Write-Output " - TXT : $TxtPath"

          $ErrorCount = ($Results | Where-Object { $_.Severity -eq 'Error' }).Count
          if ($ErrorCount -gt 0) {
              Write-Error "❌ $ErrorCount PSScriptAnalyzer errors detected."
              exit 1
          } else {
              Write-Output "✅ No PowerShell lint errors detected."
          }

      - name: 📦 Upload Lint Evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-powershell-evidence
          path: docs/_evidence/lint
          retention-days: 30
