name: 🧩 Lint PowerShell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-powershell:
    name: Run ScriptAnalyzer
    runs-on: windows-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Detect changed PowerShell files
        id: detect
        shell: pwsh
        run: |
          $changed = git diff --name-only HEAD~1 HEAD | Where-Object { $_ -match '\.(ps1|psm1|psd1)$' }
          if ($changed) {
              Write-Output "changed=true" >> $env:GITHUB_OUTPUT
              Write-Host "[lint] PowerShell changes detected: $($changed -join ', ')"
          } else {
              Write-Output "changed=false" >> $env:GITHUB_OUTPUT
              Write-Host "[lint] No PowerShell changes detected."
          }

      - name: 🔧 Run PSScriptAnalyzer
        if: steps.detect.outputs.changed == 'true'
        shell: pwsh
        run: |
          $settings = 'config\PSScriptAnalyzerSettings.psd1'
          $outDir   = 'docs\_evidence'
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          $outFile  = Join-Path $outDir ("AnalyzerReport-{0:yyyyMMdd-HHmmss}.json" -f (Get-Date))

          Write-Host "[lint] Running ScriptAnalyzer..."
          $results = Invoke-ScriptAnalyzer -Path . -Recurse -Settings $settings -Verbose:$false
          $results | ConvertTo-Json -Depth 4 | Out-File -FilePath $outFile -Encoding UTF8

          if (-not $results) {
              Write-Host "[lint] ✅ No issues found."
          } else {
              $errors = $results | Where-Object { $_.Severity -eq 'Error' }
              if ($errors) {
                  Write-Error "❌ Lint errors found."
                  exit 1
              } else {
                  Write-Host "[lint] ⚠️ Warnings found but no fatal issues."
              }
          }

      - name: 🔍 Validate Analyzer Evidence
        shell: pwsh
        run: |
          Write-Information "[ci-ps] Validating AnalyzerReport JSON..."
          $files = Get-ChildItem 'docs/_evidence' -Filter 'AnalyzerReport-*.json' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $files) { Write-Error "[ci-ps] ❌ AnalyzerReport evidence missing."; exit 1 }

          try {
              $null = Get-Content $files.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
              Write-Information "[ci-ps] ✅ $($files.Name) passed JSON verification."
          } catch {
              Write-Error "[ci-ps] ❌ Invalid AnalyzerReport JSON format."
              exit 1
          }

      - name: 💤 Skip (no PowerShell changes)
        if: steps.detect.outputs.changed == 'false'
        shell: pwsh
        run: |
          $outDir = 'docs\_evidence'
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          $outFile = Join-Path $outDir ("AnalyzerReport-{0:yyyyMMdd-HHmmss}.json" -f (Get-Date))
          @{ status = 'skipped'; reason = 'No PowerShell file changes detected.'; timestamp = (Get-Date).ToString('u') } |
          ConvertTo-Json -Depth 4 | Out-File -Encoding utf8 $outFile
          Write-Host "[lint] 💤 Lint skipped; no changes. Evidence saved to $outFile."

      - name: 📜 Upload analyzer evidence
        uses: actions/upload-artifact@v4
        with:
          name: analyzer-evidence
          path: docs/_evidence/AnalyzerReport-*.json
          retention-days: 30
